# Generated by Django 3.2.3 on 2021-05-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210523_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_on',
            new_name='created_at',
        ),
    ]
